Repository atlanhq/atlan-python, pull requests merged in 2024-08, with the labels that each got.

#366 DVX-579: Ensure the asset to which the `README` is attached has a `GUID`
  pyatlan/generator/templates/methods/attribute/readme.jinja2
  pyatlan/model/assets/core/readme.py
  tests/unit/model/readme_test.py
  tests/unit/test_model.py
Labels: bug

#367 Bump to release `2.4.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#368 DVX-563: Add support for `Azure Blob` presigned URL uploads
  pyatlan/client/atlan.py
  pyatlan/client/common.py
  pyatlan/client/constants.py
  pyatlan/client/file.py
  pyatlan/utils.py
  tests/unit/test_file_client.py
Labels: feature

#369 Bump to release `2.4.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#370 DVX-590: Added support for `GCS` presigned URL file uploads
  pyatlan/client/atlan.py
  pyatlan/client/common.py
  pyatlan/client/constants.py
  pyatlan/client/file.py
  tests/unit/test_file_client.py
Labels: feature

#371 DVX-528 Add pyatlan to conda
  .conda-envs/meta.yaml
  .github/workflows/build_and_upload_conda_packages.yaml
Labels: release

#374 DVX-565: Added `find_run_by_id` method to the `WorkflowClient`
  pyatlan/client/workflow.py
  tests/integration/test_workflow_client.py
  tests/unit/test_workflow_client.py
Labels: feature

#375 Bump to release `2.4.2`
  HISTORY.md
  pyatlan/version.txt
Labels: release
