Repository atlanhq/atlan-python, pull requests merged in 2024-03, with the labels that each got.

#257 DVX-269: Add task queue endpoint
  pyatlan/client/asset.py
  pyatlan/client/atlan.py
  pyatlan/client/constants.py
  pyatlan/client/task.py
  pyatlan/model/credential.py
  pyatlan/model/enums.py
  pyatlan/model/fluent_tasks.py
  pyatlan/model/search_log.py
  pyatlan/model/task.py
  tests/integration/test_task_client.py
  tests/unit/data/task_requests/fluent_tasks.json
  tests/unit/data/task_responses/task_search.json
  tests/unit/test_task_client.py
Labels: feature

#260 Bump to release `2.0.2`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#261 DVX-287: Set `asset_type` default value to `Asset` in `get_by_guid` method
  pyatlan/client/asset.py
  tests/integration/admin_test.py
  tests/integration/test_client.py
  tests/unit/constants.py
  tests/unit/data/asset_responses/get_by_guid.json
  tests/unit/data/asset_responses/retrieve_minimal.json
  tests/unit/test_client.py
Labels: change

#264 Fixes `to_dict` method handling of range query for `datetime` attributes
  pyatlan/model/search.py
  tests/unit/test_search_model.py
Labels: bugfix

#265 Adding AWS IoT connectors
  pyatlan/model/enums.py
Labels: feature

#266 Bump to release `2.0.3`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#267 DVX-310 Add Credential Widget to Custom Tooolkit for Python
  pyatlan/pkg/create_package_files.py
  pyatlan/pkg/models.py
  pyatlan/pkg/templates/default_template.jinja2
  pyatlan/pkg/ui.py
  pyatlan/pkg/widgets.py
  tests/unit/pkg/test_ui.py
Labels: feature

#269 DVX-315: Fixes `UserClient` create method throwing `500`
  pyatlan/client/user.py
  tests/integration/admin_test.py
  tests/unit/test_client.py
Labels: bugfix

#270 Bump to release `2.0.3`
  HISTORY.md
Labels: release

#259 DVX-277 Data mesh updates
  .github/workflows/pyatlan-test-cron.yaml
  pyatlan/errors.py
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/data_domain.jinja2
  pyatlan/generator/templates/methods/asset/data_product.jinja2
  pyatlan/generator/templates/methods/attribute/data_domain.jinja2
  pyatlan/generator/templates/methods/attribute/data_product.jinja2
  pyatlan/model/assets/asset.py
  pyatlan/model/assets/data_domain.py
  pyatlan/model/assets/data_product.py
  pyatlan/model/data_mesh.py
  pyatlan/model/enums.py
  pyatlan/model/search.py
  tests/integration/.testignore.txt
  tests/integration/data_mesh_test.py
  tests/integration/test_client.py
  tests/unit/data/data_mesh_requests/data_product_assets_dsl.json
  tests/unit/model/constants.py
  tests/unit/model/data_domain_test.py
  tests/unit/model/data_product_test.py
  tests/unit/test_search_model.py
Labels: change

#272 DVX-320: Adds `AtlanAPIResponse` model to support extra fields
  pyatlan/model/core.py
  tests/unit/test_core.py
Labels: feature

#274 DVX-323: Add an optional param to the create user method to return the created user
  pyatlan/client/user.py
  tests/integration/admin_test.py
  tests/unit/test_client.py
Labels: feature

#275 Bump to release `2.0.4`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#276 DVX-338: Adds `EnumDef` update method to add new `ElementDefs`
  .pre-commit-config.yaml
  pyatlan/cache/enum_cache.py
  pyatlan/client/typedef.py
  pyatlan/model/typedef.py
  tests/integration/custom_metadata_test.py
  tests/unit/constants.py
  tests/unit/test_client.py
  tests/unit/test_typedef_model.py
Labels: feature

#277 DVX-342: Adds `get_by_name` method to the `TypeDefClient`
  pyatlan/client/constants.py
  pyatlan/client/typedef.py
  tests/integration/custom_metadata_test.py
  tests/unit/data/typedef_responses/get_by_name.json
  tests/unit/test_client.py
Labels: feature

#279 Bump to release `2.1.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#282 DVX-331: Ensure generated process `qualified_name` still have connection prefix
  pyatlan/generator/templates/methods/attribute/process.jinja2
  pyatlan/model/assets/process.py
  tests/unit/model/constants.py
  tests/unit/model/process_test.py
Labels: bugfix

#283 Bump to release `2.1.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release
