Repository atlanhq/atlan-python, pull requests merged in 2024-11, with the labels that each got.

#417 Bump to release `2.5.7`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#418 Bump to release 2.5.8
  HISTORY.md
  pyatlan/model/enums.py
  pyatlan/version.txt
Labels: bugfix

#416 CJ-181 : `Application Container` Creator and Tests (new typedef)
  docs/asset/application.rst
  docs/asset/applicationcontainer.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/asset/application_container.jinja2
  pyatlan/generator/templates/methods/attribute/application_container.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/a_d_l_s.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/application.py
  pyatlan/model/assets/core/application_container.py
  pyatlan/model/assets/core/catalog.py
  pyatlan/model/assets/core/cosmos_mongo_d_b_collection.py
  pyatlan/model/assets/core/cosmos_mongo_d_b_database.py
  pyatlan/model/assets/core/dbt_metric.py
  pyatlan/model/assets/core/dynamo_d_b_secondary_index.py
  pyatlan/model/assets/core/mongo_d_b_collection.py
  pyatlan/model/assets/core/mongo_d_b_database.py
  pyatlan/model/assets/core/snowflake_tag.py
  pyatlan/model/assets/custom_field.py
  pyatlan/model/assets/custom_table.py
  pyatlan/model/assets/data_studio.py
  pyatlan/model/assets/data_studio_asset.py
  pyatlan/model/assets/databricks_unity_catalog_tag.py
  pyatlan/model/assets/dbt_column_process.py
  pyatlan/model/assets/dbt_process.py
  pyatlan/model/assets/dbt_tag.py
  pyatlan/model/assets/dynamo_dbtable.py
  pyatlan/model/assets/g_c_s.py
  pyatlan/model/assets/s3.py
  pyatlan/model/constants.py
  pyatlan/model/enums.py
  pyatlan/model/structs.py
  pyatlan/model/typedef.py
  tests/integration/application_asset_test.py
  tests/unit/model/application_asset_test.py
  tests/unit/model/constants.py
  tests/unit/test_model.py
Labels: feature

#419 DVX-765 Modify `Batch._track()` method to handle `AtlasGlossaryTerm`
  pyatlan/client/asset.py
  tests/integration/test_index_search.py
  tests/unit/test_client.py
Labels: bugfix

#423 FT-783: Changed fields to optional to ensure capture results without any Pydantic `ValidationError`
  pyatlan/client/workflow.py
  pyatlan/model/workflow.py
  pyatlan/utils.py
  tests/integration/test_workflow_client.py
  tests/unit/constants.py
  tests/unit/test_lineage.py
  tests/unit/test_workflow_client.py
Labels: change

#420 DVX-777: Added `username` and extra `fields` to the `CredentialResponse`
  pyatlan/model/credential.py
  tests/unit/test_credential_client.py
Labels: feature

#428 FT-773: Add X-Atlan-Client-Origin header to session requests
  pyatlan/client/atlan.py
  tests/unit/test_client.py
Labels: feature

#427 FT-778: Add credential list endpoint to the SDKs
  pyatlan/client/constants.py
  pyatlan/client/credential.py
  pyatlan/model/credential.py
  tests/integration/test_workflow_client.py
  tests/unit/test_credential_client.py
Labels: feature

#430 Bump to release `2.6.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release
