Repository atlanhq/atlan-python, pull requests merged in 2024-05, with the labels that each got.

#306 req-changes: Use string presigned URL
  pyatlan/client/file.py
  pyatlan/model/file.py
  tests/integration/test_client.py
  tests/integration/test_file_client.py
  tests/integration/test_index_search.py
  tests/unit/constants.py
  tests/unit/test_file_client.py
Labels: change

#307 Bump to release `2.1.7`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#309 DVX-417: Fixes API token deletion in test cleanup
  tests/integration/purpose_test.py
  tests/integration/requests_test.py
Labels: bugfix

#308 DVX-404: Adds support for `Snowflake Miner`
  pyatlan/model/packages/__init__.py
  pyatlan/model/packages/base/miner.py
  pyatlan/model/packages/snowflake_miner.py
  tests/unit/data/package_requests/snowflake_miner_default.json
  tests/unit/data/package_requests/snowflake_miner_s3_offline.json
  tests/unit/data/package_requests/snowflake_miner_source.json
  tests/unit/test_packages.py
Labels: feature

#312 DVX-420: Adds further connector types
  pyatlan/model/enums.py
Labels: feature

#311 DVX-416: Add new optional "depth" attribute to `Referenceable`
  pyatlan/generator/templates/referenceable_attributes.jinja2
  pyatlan/model/assets/referenceable.py
  tests/integration/lineage_test.py
  tests/unit/data/lineage_responses/lineage_list.json
  tests/unit/test_client.py
Labels: feature

#314 DVX-405: Adds support for scheduling workflow runs
  docs/requirements.txt
  pyatlan/client/constants.py
  pyatlan/client/workflow.py
  pyatlan/model/workflow.py
  requirements.txt
  tests/integration/test_client.py
  tests/integration/test_workflow_client.py
  tests/unit/constants.py
  tests/unit/test_workflow_client.py
Labels: feature

#320 DVX-432: Utilize generated `atlas core` enums in the template
  pyatlan/generator/class_generator.py
  pyatlan/generator/templates/module.jinja2
Labels: bug

#325 Adds `pyatlan-formatter`
  pyatlan-formatter
  pyatlan/generator/class_generator.py
  pyatlan/generator/templates/module.jinja2
Labels: feature

#324 Bump to release `2.1.9`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#326 Fixes typo in `IAM` role methods of `DynamoDB` and `PostgreSQL` crawlers
  pyatlan/model/packages/dynamo_d_b_crawler.py
  pyatlan/model/packages/postgres_crawler.py
  tests/unit/test_packages.py
Labels: bug

#328 DVX-428: Set `connector_name` from provided `connection_qualified_name`
  pyatlan/generator/templates/methods/asset/database.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_account.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_container.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_object.jinja2
  pyatlan/generator/templates/methods/attribute/a_p_i_path.jinja2
  pyatlan/generator/templates/methods/attribute/a_p_i_spec.jinja2
  pyatlan/generator/templates/methods/attribute/airflow_dag.jinja2
  pyatlan/generator/templates/methods/attribute/airflow_task.jinja2
  pyatlan/generator/templates/methods/attribute/column.jinja2
  pyatlan/generator/templates/methods/attribute/data_studio_asset.jinja2
  pyatlan/generator/templates/methods/attribute/database.jinja2
  pyatlan/generator/templates/methods/attribute/file.jinja2
  pyatlan/generator/templates/methods/attribute/g_c_s_bucket.jinja2
  pyatlan/generator/templates/methods/attribute/g_c_s_object.jinja2
  pyatlan/generator/templates/methods/attribute/materialised_view.jinja2
  pyatlan/generator/templates/methods/attribute/preset_chart.jinja2
  pyatlan/generator/templates/methods/attribute/preset_dashboard.jinja2
  pyatlan/generator/templates/methods/attribute/preset_dataset.jinja2
  pyatlan/generator/templates/methods/attribute/preset_workspace.jinja2
  pyatlan/generator/templates/methods/attribute/schema.jinja2
  pyatlan/generator/templates/methods/attribute/table.jinja2
  pyatlan/generator/templates/methods/attribute/view.jinja2
  pyatlan/model/assets/a_d_l_s_account.py
  pyatlan/model/assets/a_d_l_s_container.py
  pyatlan/model/assets/a_d_l_s_object.py
  pyatlan/model/assets/a_p_i_path.py
  pyatlan/model/assets/a_p_i_spec.py
  pyatlan/model/assets/airflow_dag.py
  pyatlan/model/assets/airflow_task.py
  pyatlan/model/assets/column.py
  pyatlan/model/assets/data_studio_asset.py
  pyatlan/model/assets/database.py
  pyatlan/model/assets/file.py
  pyatlan/model/assets/g_c_s_bucket.py
  pyatlan/model/assets/g_c_s_object.py
  pyatlan/model/assets/materialised_view.py
  pyatlan/model/assets/preset_chart.py
  pyatlan/model/assets/preset_dashboard.py
  pyatlan/model/assets/preset_dataset.py
  pyatlan/model/assets/preset_workspace.py
  pyatlan/model/assets/schema.py
  pyatlan/model/assets/table.py
  pyatlan/model/assets/view.py
  pyatlan/model/enums.py
  tests/integration/file_test.py
  tests/unit/model/file_test.py
Labels: bug

#329 DVX-417: Added fallback delete mechanism to API tokens in tests
  tests/integration/purpose_test.py
  tests/integration/requests_test.py
Labels: bug

#331 DVX-444 Added `find_by_name` methods for domain and products
  docs/asset/cognos.rst
  docs/asset/cognosdashboard.rst
  docs/asset/cognosdatasource.rst
  docs/asset/cognosexploration.rst
  docs/asset/cognosfile.rst
  docs/asset/cognosfolder.rst
  docs/asset/cognosmodule.rst
  docs/asset/cognospackage.rst
  docs/asset/cognosreport.rst
  docs/asset/stakeholder.rst
  docs/asset/stakeholdertitle.rst
  docs/assets.rst
  pyatlan/client/asset.py
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/data_mesh.jinja2
  pyatlan/generator/templates/methods/attribute/data_domain.jinja2
  pyatlan/generator/templates/methods/attribute/data_product.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/cognos.py
  pyatlan/model/assets/cognos_dashboard.py
  pyatlan/model/assets/cognos_datasource.py
  pyatlan/model/assets/cognos_exploration.py
  pyatlan/model/assets/cognos_file.py
  pyatlan/model/assets/cognos_folder.py
  pyatlan/model/assets/cognos_module.py
  pyatlan/model/assets/cognos_package.py
  pyatlan/model/assets/cognos_report.py
  pyatlan/model/assets/data_domain.py
  pyatlan/model/assets/data_mesh.py
  pyatlan/model/assets/data_product.py
  pyatlan/model/assets/database.py
  pyatlan/model/assets/stakeholder.py
  pyatlan/model/assets/stakeholder_title.py
  tests/integration/data_mesh_test.py
  tests/unit/constants.py
  tests/unit/model/constants.py
  tests/unit/model/data_domain_test.py
  tests/unit/model/data_product_test.py
  tests/unit/test_client.py
Labels: bug, feature

#332 Bump to release `2.2.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#280 workflow api's for schedule queries
  pyatlan/client/constants.py
  pyatlan/client/workflow.py
  pyatlan/model/workflow.py
  tests/unit/constants.py
  tests/unit/test_workflow_client.py
Labels: feature

#334 DVX-371: Added support for `includeClassificationNames` in `IndexSearchRequest`
  pyatlan/model/search.py
  tests/integration/test_client.py
Labels: feature

#335 Updated the `pydantic` dependency to provide more flexibility for users
  requirements.txt
Labels: dependencies

#338 Bump to release `2.2.2`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#339 DVX-495: Added support for the `Connection Delete` package
  pyatlan/model/packages/__init__.py
  pyatlan/model/packages/connection_delete.py
  tests/unit/data/package_requests/connection_delete_hard.json
  tests/unit/data/package_requests/connection_delete_soft.json
  tests/unit/test_packages.py
Labels: feature

#341 DVX-481: Added support for handling data domains and products in custom metadata
  pyatlan/model/constants.py
  pyatlan/model/enums.py
  pyatlan/model/typedef.py
  tests/integration/data_mesh_test.py
  tests/unit/constants.py
  tests/unit/test_typedef_model.py
Labels: feature
