Repository atlanhq/atlan-python, pull requests merged in 2024-12, with the labels that each got.

#431 FT-814:Add projection support for groups endpoint
  pyatlan/client/constants.py
  pyatlan/client/group.py
  pyatlan/model/group.py
  tests/integration/admin_test.py
  tests/unit/test_client.py
Labels: feature

#433 Bump realease 2.6.2
  HISTORY.md
  pyatlan/version.txt
Labels: release

#435 Bump to release `2.7.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#436 Updated integration test to align to new tenant setup
  tests/integration/purpose_test.py
  tests/integration/test_task_client.py
  tests/integration/test_workflow_client.py
Labels: change

#437 FT-838: Fix generator to correctly handle the DOMAIN_GUIDS keyword field
  pyatlan/generator/class_generator.py
  pyatlan/model/assets/business_policy_incident.py
  pyatlan/model/assets/core/asset.py
  pyatlan/model/enums.py
Labels: bugfix

#439 FT-527: Added `update_only`, `case_insensitive` and `table_agnostic` options to `Batch`
  docs/assets.rst
  pyatlan/client/asset.py
  pyatlan/generator/templates/methods/asset/asset.jinja2
  pyatlan/generator/templates/methods/asset/atlas_glossary_category.jinja2
  pyatlan/generator/templates/methods/asset/atlas_glossary_term.jinja2
  pyatlan/generator/templates/methods/asset/auth_policy.jinja2
  pyatlan/generator/templates/methods/asset/data_domain.jinja2
  pyatlan/generator/templates/methods/asset/data_product.jinja2
  pyatlan/generator/templates/methods/asset/persona.jinja2
  pyatlan/generator/templates/methods/asset/purpose.jinja2
  pyatlan/generator/templates/module.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/business_process_model.py
  pyatlan/model/assets/business_process_model_entity.py
  pyatlan/model/assets/core/asset.py
  pyatlan/model/assets/core/atlas_glossary_category.py
  pyatlan/model/assets/core/atlas_glossary_term.py
  pyatlan/model/assets/core/auth_policy.py
  pyatlan/model/assets/core/data_domain.py
  pyatlan/model/assets/core/data_product.py
  pyatlan/model/assets/core/materialised_view.py
  pyatlan/model/assets/core/persona.py
  pyatlan/model/assets/core/table.py
  pyatlan/model/assets/core/view.py
  pyatlan/model/assets/purpose.py
  pyatlan/model/enums.py
  pyatlan/model/structs.py
  tests/integration/test_asset_batch.py
  tests/unit/test_client.py
Labels: feature

#442 CXD-329 : Adding new connector
  pyatlan/model/enums.py
Labels: feature

#440 FT-650 Add timeout to pyatlan client.
  pyatlan/client/asset.py
  pyatlan/client/atlan.py
  tests/integration/lineage_test.py
  tests/integration/purpose_test.py
  tests/integration/test_index_search.py
Labels: feature, change

#443 FT-650: Remove unused lineage test assertions
  tests/integration/lineage_test.py
Labels: cleanup

#445 FT-820 Add SnowflakeDynamicTable as possible parent-type.
  pyatlan/generator/templates/methods/attribute/column.jinja2
  pyatlan/model/assets/core/column.py
  tests/unit/model/a_p_i_object_test.py
  tests/unit/model/a_p_i_query_test.py
  tests/unit/model/application_test.py
  tests/unit/model/column_test.py
Labels: feature

#438 FT-840: Improve unhandled exception message logging
  pyatlan/client/atlan.py
  pyatlan/errors.py
  tests/integration/glossary_test.py
  tests/integration/test_client.py
  tests/unit/test_client.py
Labels: change

#446 FT-617: Added exposure of source-specific custom attributes
  pyatlan/model/assets/core/referenceable.py
  tests/integration/test_index_search.py
Labels: feature

#444 FT-790: Remove possibility of overrunning search pages when total results are just under the threshold
  pyatlan/client/asset.py
Labels: bugfix

#441 FT-818: Implement query rewrite for large AuditSearch responses
  pyatlan/client/asset.py
  pyatlan/client/audit.py
  pyatlan/errors.py
  pyatlan/model/audit.py
  tests/integration/test_client.py
  tests/unit/data/search_responses/audit_search_paging.json
  tests/unit/test_audit_search.py
Labels: feature

#447 FT-865: Fixed timestamp paging returns incomplete results
  pyatlan/client/asset.py
  pyatlan/model/audit.py
  tests/integration/test_index_search.py
Labels: bug

#448 Bump to major release 3.0.0
  HISTORY.md
  pyatlan/client/asset.py
  pyatlan/version.txt
Labels: release

#450 FT-401: Added support for token retry authentication when it expires (401)
  pyatlan/client/atlan.py
  pyatlan/client/constants.py
  pyatlan/client/impersonate.py
  pyatlan/errors.py
  pyatlan/model/response.py
  pyatlan/pkg/utils.py
  tests/integration/test_client.py
  tests/unit/test_client.py
Labels: feature

#449 FT-853: Implement query rewrite for Searchlog responses
  pyatlan/client/search_log.py
  pyatlan/errors.py
  pyatlan/model/search_log.py
  tests/integration/test_client.py
  tests/unit/data/search_responses/search_log_search_paging.json
  tests/unit/test_search_log_search.py
Labels: feature

#451 Bump to release `3.1.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#452 DT-875 Fix issue with private property in constructor
  pyatlan/pkg/utils.py
Labels: bugfix

#453 Bump to release `3.1.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#454 FT-842: Enabled the use of `Retry-After` header value for handling rate-limit retries
  pyatlan/client/atlan.py
Labels: feature

#456 CXD-304 | Added new `dataverse` connector
  pyatlan/model/enums.py
Labels: feature

#455 FT-874: Fix the unit test and integration test in Audit Search
  tests/integration/test_client.py
  tests/unit/data/search_responses/audit_search_paging.json
  tests/unit/test_audit_search.py
Labels: bugfix

#459 FT-864 Add logic for open telementry logging.
  pyatlan/client/atlan.py
  pyatlan/pkg/utils.py
  pyatlan/utils.py
  tests/integration/test_index_search.py
Labels: feature

#461 FT-609: Added `creator()` for Insights objects (`Collection`, `Folder`, `Query`)
  docs/asset/azureservicebusschema.rst
  docs/asset/bigquerytag.rst
  docs/assets.rst
  pyatlan/errors.py
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/collection.jinja2
  pyatlan/generator/templates/methods/asset/folder.jinja2
  pyatlan/generator/templates/methods/asset/query.jinja2
  pyatlan/generator/templates/methods/attribute/collection.jinja2
  pyatlan/generator/templates/methods/attribute/folder.jinja2
  pyatlan/generator/templates/methods/attribute/query.jinja2
  pyatlan/generator/templates/referenceable_attributes.jinja2
  pyatlan/generator/templates/referenceable_methods.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/azure_service_bus.py
  pyatlan/model/assets/azure_service_bus_schema.py
  pyatlan/model/assets/azure_service_bus_topic.py
  pyatlan/model/assets/bigquery_tag.py
  pyatlan/model/assets/collection.py
  pyatlan/model/assets/core/data_contract.py
  pyatlan/model/assets/core/folder.py
  pyatlan/model/assets/core/query.py
  pyatlan/model/assets/core/referenceable.py
  pyatlan/model/structs.py
  tests/integration/insights_test.py
Labels: feature

#457 CXD-347 : Support for `Anaplan` typedefs
  docs/asset/anaplan.rst
  docs/asset/anaplanapp.rst
  docs/asset/anaplandimension.rst
  docs/asset/anaplanlineitem.rst
  docs/asset/anaplanlist.rst
  docs/asset/anaplanmodel.rst
  docs/asset/anaplanmodule.rst
  docs/asset/anaplanpage.rst
  docs/asset/anaplanview.rst
  docs/asset/anaplanworkspace.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/asset/anaplan_app.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_dimension.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_line_item.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_list.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_model.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_module.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_page.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_view.jinja2
  pyatlan/generator/templates/methods/asset/anaplan_workspace.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_app.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_dimension.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_line_item.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_list.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_model.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_module.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_page.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_view.jinja2
  pyatlan/generator/templates/methods/attribute/anaplan_workspace.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/anaplan.py
  pyatlan/model/assets/anaplan_app.py
  pyatlan/model/assets/anaplan_dimension.py
  pyatlan/model/assets/anaplan_line_item.py
  pyatlan/model/assets/anaplan_list.py
  pyatlan/model/assets/anaplan_model.py
  pyatlan/model/assets/anaplan_module.py
  pyatlan/model/assets/anaplan_page.py
  pyatlan/model/assets/anaplan_view.py
  pyatlan/model/assets/anaplan_workspace.py
  pyatlan/model/constants.py
  pyatlan/model/enums.py
  pyatlan/model/typedef.py
  tests/integration/anaplan_asset_test.py
  tests/unit/model/anaplan_app_test.py
  tests/unit/model/anaplan_dimension_test.py
  tests/unit/model/anaplan_line_item_test.py
  tests/unit/model/anaplan_list_test.py
  tests/unit/model/anaplan_model_test.py
  tests/unit/model/anaplan_module_test.py
  tests/unit/model/anaplan_page_test.py
  tests/unit/model/anaplan_view_test.py
  tests/unit/model/anaplan_workspace_test.py
  tests/unit/model/constants.py
  tests/unit/test_model.py
Labels: feature

#463 Bump to release 3.1.2
  .conda-envs/meta.yaml
  HISTORY.md
  docs/requirements.txt
  pyatlan/version.txt
  requirements.txt
Labels: release
