Repository atlanhq/atlan-python, pull requests merged in 2024-06, with the labels that each got.

#344 DVX-500 Update to include user action when throwing an exception
  pyatlan/errors.py
  tests/integration/glossary_test.py
  tests/unit/test_lineage.py
Labels: feature

#345 Bump to release `2.2.3`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#346 DVX-506: Updated latest set of Phosphor icons in `AtlanIcon` enum
  pyatlan/model/enums.py
Labels: feature

#348 DVX-398: Removed the required kwarg (`name`) from the `DataContract` `creator()`
  pyatlan/errors.py
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/data_contract.jinja2
  pyatlan/generator/templates/methods/attribute/data_contract.jinja2
  pyatlan/model/assets/data_contract.py
  tests/integration/data_mesh_test.py
  tests/unit/model/constants.py
  tests/unit/model/data_contract_test.py
Labels: change

#349 Bump to release `2.2.4`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#351 DVX-488: Implement infinite paging approach
  pyatlan/client/asset.py
  pyatlan/errors.py
  pyatlan/model/fluent_search.py
  tests/integration/test_index_search.py
  tests/unit/data/search_responses/index_search_paging.json
  tests/unit/test_client.py
Labels: feature

#352 Bump to release `2.3.0`
  HISTORY.md
  pyatlan/client/asset.py
  pyatlan/errors.py
  pyatlan/model/fluent_search.py
  pyatlan/model/search.py
  pyatlan/version.txt
  tests/integration/test_index_search.py
  tests/unit/test_client.py
  tests/unit/test_search_model.py
Labels: release
