Repository atlanhq/atlan-python, pull requests merged in 2024-10, with the labels that each got.

#393 CXD-237 | Added New connectors
  pyatlan/model/enums.py
Labels: feature

#396 DVX-657: Added experimental support for serde on the data contract spec
  pyatlan/client/contract.py
  pyatlan/generator/templates/methods/asset/data_contract.jinja2
  pyatlan/generator/templates/methods/attribute/data_contract.jinja2
  pyatlan/model/assets/core/data_contract.py
  pyatlan/model/contract.py
  pyatlan/model/core.py
  pyatlan/model/enums.py
  tests/integration/data_mesh_test.py
  tests/integration/test_sql_assets.py
  tests/unit/model/constants.py
  tests/unit/model/data_contract_test.py
Labels: feature

#394 DVX-522: Added initial support for sending `OpenLineage` events
  pyatlan/client/atlan.py
  pyatlan/client/common.py
  pyatlan/client/constants.py
  pyatlan/client/open_lineage.py
  pyatlan/errors.py
  pyatlan/model/enums.py
  pyatlan/model/open_lineage/__init__.py
  pyatlan/model/open_lineage/base.py
  pyatlan/model/open_lineage/column_lineage_dataset.py
  pyatlan/model/open_lineage/dataset.py
  pyatlan/model/open_lineage/event.py
  pyatlan/model/open_lineage/facet.py
  pyatlan/model/open_lineage/input_dataset.py
  pyatlan/model/open_lineage/job.py
  pyatlan/model/open_lineage/output_dataset.py
  pyatlan/model/open_lineage/run.py
  pyatlan/model/open_lineage/utils.py
  pyatlan/utils.py
  requirements.txt
  tests/unit/data/open_lineage_requests/event_complete.json
  tests/unit/data/open_lineage_requests/event_start.json
  tests/unit/model/open_lineage/__init__.py
  tests/unit/model/open_lineage/open_lineage_test.py
Labels: feature

#397 Bump to release `2.5.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#398 Bump to release 2.5.1
  HISTORY.md
  pyatlan/version.txt
  requirements.txt
Labels: release

#399 DVX-684: Updated `TableauDatasource.upstream_tables` and `upstream_datasources` types
  docs/asset/adf.rst
  docs/asset/adfactivity.rst
  docs/asset/adfdataflow.rst
  docs/asset/adfdataset.rst
  docs/asset/adflinkedservice.rst
  docs/asset/adfpipeline.rst
  docs/assets.rst
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/macros.jinja2
  pyatlan/generator/templates/module.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/a_d_f.py
  pyatlan/model/assets/core/adf_activity.py
  pyatlan/model/assets/core/adf_dataflow.py
  pyatlan/model/assets/core/adf_dataset.py
  pyatlan/model/assets/core/adf_linkedservice.py
  pyatlan/model/assets/core/adf_pipeline.py
  pyatlan/model/assets/core/asset.py
  pyatlan/model/assets/core/column.py
  pyatlan/model/assets/core/column_process.py
  pyatlan/model/assets/core/process.py
  pyatlan/model/assets/d_m.py
  pyatlan/model/assets/d_m_attribute.py
  pyatlan/model/assets/d_m_attribute_association.py
  pyatlan/model/assets/d_m_data_model.py
  pyatlan/model/assets/d_m_entity.py
  pyatlan/model/assets/d_m_entity_association.py
  pyatlan/model/assets/d_m_version.py
  pyatlan/model/assets/dbt_column_process.py
  pyatlan/model/assets/dbt_process.py
  pyatlan/model/assets/model.py
  pyatlan/model/assets/tableau_datasource.py
  pyatlan/model/assets/tableau_datasource_field.py
  pyatlan/model/assets/task.py
  pyatlan/model/enums.py
  pyatlan/model/structs.py
  pyatlan/pkg/models.py
  tests/unit/test_model.py
Labels: change

#400 Bump to release `2.5.2`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#401 DVX-641: Added `immediateNeighbors` option and fixes missing lineage response details
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/referenceable_attributes.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/referenceable.py
  pyatlan/model/lineage.py
  pyatlan/model/lineage_ref.py
  tests/integration/lineage_test.py
Labels: feature

#404 CXD-251 | Added inRiver new connectors
  pyatlan/model/enums.py
Labels: feature

#403 CXD-212 : apiObject, apiQuery and apiField creator methods and tests
  docs/asset/apifield.rst
  docs/asset/apiobject.rst
  docs/asset/apiquery.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/asset/a_p_i_field.jinja2
  pyatlan/generator/templates/methods/asset/a_p_i_object.jinja2
  pyatlan/generator/templates/methods/asset/a_p_i_query.jinja2
  pyatlan/generator/templates/methods/attribute/a_p_i_field.jinja2
  pyatlan/generator/templates/methods/attribute/a_p_i_object.jinja2
  pyatlan/generator/templates/methods/attribute/a_p_i_query.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/a_p_i.py
  pyatlan/model/assets/a_p_i_field.py
  pyatlan/model/assets/a_p_i_object.py
  pyatlan/model/assets/a_p_i_query.py
  pyatlan/model/constants.py
  pyatlan/model/enums.py
  pyatlan/model/typedef.py
  tests/integration/api_asset_test.py
  tests/unit/model/a_p_i_field_test.py
  tests/unit/model/a_p_i_object_test.py
  tests/unit/model/a_p_i_query_test.py
  tests/unit/model/constants.py
  tests/unit/test_model.py
Labels: feature

#405 Bump to release 2.5.3
  HISTORY.md
  pyatlan/model/lineage.py
  pyatlan/version.txt
Labels: release

#406 DVX-701: Fixed test_sql_assets: Ensured `Readme` asset is passed by `ref_by_guid()`
  tests/integration/test_sql_assets.py
Labels: test

#407 DVX-709: Implement caching for `Connection` and `SourceTag`
  pyatlan/cache/abstract_asset_cache.py
  pyatlan/cache/connection_cache.py
  pyatlan/cache/source_tag_cache.py
  pyatlan/errors.py
  pyatlan/model/enums.py
  tests/unit/test_connection_cache.py
  tests/unit/test_source_cache.py
Labels: feature

#408 DVX-648: Added support for assigning a `SourceTag` with a value to asset
  pyatlan/model/core.py
  pyatlan/model/structs.py
  pyatlan/utils.py
  tests/integration/test_index_search.py
Labels: feature

#409 Bump to release `2.5.4`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#410 DVX-723: Fixed `AtlanError` message for unescaped curly braces in `response.text`
  pyatlan/errors.py
  tests/unit/test_client.py
Labels: bug

#411 Bump to release `2.5.5`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#412 DVX-727: Fixed `Readme.creator()` to send `asset.trim_to_reference()` instead of the complete `asset`
  docs/asset/fivetran.rst
  docs/asset/fivetranconnector.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/attribute/readme.jinja2
  pyatlan/generator/templates/structs.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/a_d_l_s_container.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/calculation_view.py
  pyatlan/model/assets/core/catalog.py
  pyatlan/model/assets/core/fivetran.py
  pyatlan/model/assets/core/fivetran_connector.py
  pyatlan/model/assets/core/function.py
  pyatlan/model/assets/core/matillion_component.py
  pyatlan/model/assets/core/model.py
  pyatlan/model/assets/core/model_attribute.py
  pyatlan/model/assets/core/model_attribute_association.py
  pyatlan/model/assets/core/model_data_model.py
  pyatlan/model/assets/core/model_entity.py
  pyatlan/model/assets/core/model_entity_association.py
  pyatlan/model/assets/core/model_version.py
  pyatlan/model/assets/core/process.py
  pyatlan/model/assets/core/readme.py
  pyatlan/model/assets/data_studio.py
  pyatlan/model/assets/dbt_column_process.py
  pyatlan/model/assets/dbt_process.py
  pyatlan/model/assets/domo_dataset.py
  pyatlan/model/assets/g_c_s.py
  pyatlan/model/assets/mode_query.py
  pyatlan/model/assets/sigma_page.py
  pyatlan/model/assets/sisense_datamodel_table.py
  pyatlan/model/enums.py
  pyatlan/model/structs.py
  tests/integration/test_sql_assets.py
  tests/unit/model/readme_test.py
Labels: bugfix

#413 Bump to release `2.5.6`
  HISTORY.md
  pyatlan/version.txt
  tests/integration/test_index_search.py
Labels: release
