Repository atlanhq/atlan-python, pull requests merged in 2025-01, with the labels that each got.

#464 FT-679 Modified find_by_type to use regular expression
  pyatlan/client/workflow.py
Labels: bugfix

#466 FT-876: Added `OSV` vulnerability-scan job to the CI
  .github/workflows/pyatlan-pr.yaml
Labels: feature

#458 FT-843: Implement GET operation that takes a list of attributes and relationships
  pyatlan/client/asset.py
  pyatlan/samples/events/lambda_scorer.py
  pyatlan/test_utils/__init__.py
  tests/integration/adls_asset_test.py
  tests/integration/airflow_asset_test.py
  tests/integration/api_asset_test.py
  tests/integration/app_asset_test.py
  tests/integration/azure_event_hub_asset_test.py
  tests/integration/connection_test.py
  tests/integration/custom_metadata_test.py
  tests/integration/data_mesh_test.py
  tests/integration/data_studio_asset_test.py
  tests/integration/file_test.py
  tests/integration/gcs_asset_test.py
  tests/integration/glossary_test.py
  tests/integration/kafka_asset_test.py
  tests/integration/lineage_test.py
  tests/integration/persona_test.py
  tests/integration/preset_asset_test.py
  tests/integration/purpose_test.py
  tests/integration/s3_asset_test.py
  tests/integration/superset_asset_test.py
  tests/integration/test_client.py
  tests/integration/test_index_search.py
  tests/integration/test_sql_assets.py
  tests/integration/test_task_client.py
  tests/integration/utils.py
  tests/unit/test_client.py
Labels: feature

#465 FT-887: Unable to append terms to a particular TableauDatasource
  pyatlan/client/asset.py
  pyatlan/model/core.py
  tests/integration/test_client.py
  tests/unit/test_client.py
Labels: bugfix

#468 FT-892: Ensure create_with_prefix sets the s3BucketName attribute
  pyatlan/model/assets/s3_object.py
  tests/integration/s3_asset_test.py
  tests/unit/model/s3object_test.py
Labels: bugfix

#472 CXD-304 | Support for Dataverse typedefs
  pyatlan/generator/templates/methods/asset/dataverse_attribute.jinja2
  pyatlan/generator/templates/methods/asset/dataverse_entity.jinja2
  pyatlan/generator/templates/methods/attribute/dataverse_attribute.jinja2
  pyatlan/generator/templates/methods/attribute/dataverse_entity.jinja2
  pyatlan/model/assets/dataverse_attribute.py
  pyatlan/model/assets/dataverse_entity.py
  pyatlan/model/constants.py
  pyatlan/model/structs.py
  pyatlan/model/typedef.py
  tests/integration/dataverse_asset_test.py
  tests/unit/model/constants.py
  tests/unit/model/dataverse_attribute_test.py
  tests/unit/model/dataverse_entity_test.py
  tests/unit/test_model.py
Labels: feature

#475 CXD-379 | Support for Custom typedefs
  docs/asset/customentity.rst
  docs/asset/powerbidataflowentitycolumn.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/asset/custom_entity.jinja2
  pyatlan/generator/templates/methods/attribute/custom_entity.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/power_b_i_dataflow.py
  pyatlan/model/assets/core/power_b_i_dataflow_entity_column.py
  pyatlan/model/assets/core/power_b_i_datasource.py
  pyatlan/model/assets/custom.py
  pyatlan/model/assets/custom_entity.py
  pyatlan/model/constants.py
  pyatlan/model/enums.py
  pyatlan/model/typedef.py
  tests/integration/custom_asset_test.py
  tests/unit/model/constants.py
  tests/unit/model/custom_entity_test.py
  tests/unit/test_model.py
Labels: feature

#474 FT-861: Added `Databricks` crawler and miner
  pyatlan/model/packages/__init__.py
  pyatlan/model/packages/base/crawler.py
  pyatlan/model/packages/base/miner.py
  pyatlan/model/packages/databricks_crawler.py
  pyatlan/model/packages/databricks_miner.py
  pyatlan/model/packages/mongodb_crawler.py
  pyatlan/model/packages/snowflake_miner.py
  tests/unit/data/package_requests/databricks_aws.json
  tests/unit/data/package_requests/databricks_azure.json
  tests/unit/data/package_requests/databricks_basic_jdbc.json
  tests/unit/data/package_requests/databricks_basic_rest.json
  tests/unit/data/package_requests/databricks_miner_offline.json
  tests/unit/data/package_requests/databricks_miner_popularity_rest.json
  tests/unit/data/package_requests/databricks_miner_popularity_system_table.json
  tests/unit/data/package_requests/databricks_miner_rest.json
  tests/unit/data/package_requests/databricks_miner_system_table.json
  tests/unit/data/package_requests/databricks_offline.json
  tests/unit/data/package_requests/mongodb_basic.json
  tests/unit/test_packages.py
Labels: feature

#476 FT-897: Fixing the unit tests for append terms, replace terms and remove terms
  tests/unit/test_client.py
Labels: test

#473 FT-896: Implement creators and updaters for TablePartition
  pyatlan/generator/templates/methods/asset/column.jinja2
  pyatlan/generator/templates/methods/asset/table_partition.jinja2
  pyatlan/generator/templates/methods/attribute/column.jinja2
  pyatlan/generator/templates/methods/attribute/table_partition.jinja2
  pyatlan/model/assets/core/column.py
  pyatlan/model/assets/core/table_partition.py
  tests/integration/test_sql_assets.py
  tests/unit/model/constants.py
  tests/unit/model/table_partition_test.py
Labels: feature

#478 Bump to release `4.0.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#482 APP-4786 Add logic to log unhandled exceptions.
  .github/workflows/pyatlan-codeql.yaml
  pyatlan/pkg/utils.py
Labels: feature

#479 FT-653: Provide helper to create OpenLineage connection
  pyatlan/client/constants.py
  pyatlan/client/open_lineage.py
  tests/integration/test_open_lineage.py
Labels: feature

#483 APP-4781 | Handled deleted `AtlanTagName` gracefully in `Purpose` asset deserialization
  pyatlan/model/core.py
  tests/unit/test_atlan_tag_name.py
Labels: bugfix

#480 FT-585: Added Installation for development section to README.md
  .env.example
  README.md
Labels: documentation

#486 APP-4603: Added support for `LineageBuilder` and `LineageGenerator` packages
  pyatlan/model/enums.py
  pyatlan/model/packages/__init__.py
  pyatlan/model/packages/lineage_builder.py
  pyatlan/model/packages/lineage_generator_nt.py
  tests/unit/data/package_requests/lineage_builder_adls.json
  tests/unit/data/package_requests/lineage_builder_gcs.json
  tests/unit/data/package_requests/lineage_builder_s3.json
  tests/unit/data/package_requests/lineage_generator_default.json
  tests/unit/data/package_requests/lineage_generator_full.json
  tests/unit/test_packages.py
Labels: feature

#488 APP-5002: Fixed maximum token TTE to `5` years
  pyatlan/model/api_tokens.py
Labels: bug

#493 APP-5054: Increased default read timeout to `15` minutes for `AtlanClient`
  pyatlan/client/atlan.py
Labels: change

#492 APP-5050: Extended `WorkflowClient.run()` method to accept raw workflow `JSON` (str)
  pyatlan/client/workflow.py
  pyatlan/utils.py
  tests/unit/constants.py
  tests/unit/test_workflow_client.py
Labels: feature

#487 APP-4749: Added support for Python `3.12` and `3.13.1` (latest)
  .github/workflows/pyatlan-pr.yaml
  pyatlan/cache/abstract_asset_cache.py
  pyatlan/client/open_lineage.py
  pyatlan/client/workflow.py
  pyatlan/model/fields/atlan_fields.py
  setup.py
  tests/integration/test_file_client.py
  tests/unit/test_audit_search.py
  tests/unit/test_client.py
  tests/unit/test_search_log_search.py
  tests/unit/test_search_model.py
  tests/unit/test_workflow_client.py
Labels: dependencies, change

#494 Bump to release `4.1.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#481 CXD-321 : ApplicationField typedef addition
  docs/asset/applicationfield.rst
  docs/assets.rst
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/application_field.jinja2
  pyatlan/generator/templates/methods/attribute/application_field.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/business_policy.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/application.py
  pyatlan/model/assets/core/application_field.py
  pyatlan/model/assets/core/asset.py
  pyatlan/model/assets/core/power_b_i_column.py
  pyatlan/model/assets/core/power_b_i_dashboard.py
  pyatlan/model/assets/core/power_b_i_dataflow.py
  pyatlan/model/assets/core/power_b_i_dataset.py
  pyatlan/model/assets/core/power_b_i_measure.py
  pyatlan/model/assets/core/power_b_i_page.py
  pyatlan/model/assets/core/power_b_i_report.py
  pyatlan/model/assets/core/power_b_i_table.py
  pyatlan/model/assets/core/power_b_i_tile.py
  pyatlan/model/assets/tableau_calculated_field.py
  pyatlan/model/assets/tableau_dashboard.py
  pyatlan/model/assets/tableau_datasource.py
  pyatlan/model/assets/tableau_datasource_field.py
  pyatlan/model/assets/tableau_flow.py
  pyatlan/model/assets/tableau_metric.py
  pyatlan/model/assets/tableau_workbook.py
  pyatlan/model/assets/tableau_worksheet.py
  pyatlan/model/assets/workflow.py
  pyatlan/model/assets/workflow_run.py
  pyatlan/model/constants.py
  pyatlan/model/structs.py
  pyatlan/model/typedef.py
  tests/integration/app_asset_test.py
  tests/unit/model/application_field_test.py
  tests/unit/model/constants.py
  tests/unit/test_model.py
Labels: feature
