Repository atlanhq/atlan-python, pull requests merged in 2025-05, with the labels that each got.

#625 APP-6565: Added support for dynamic extension of `AtlanConnectorType` for custom connectors
  pyatlan/cache/connection_cache.py
  pyatlan/model/enums.py
  pyatlan/utils.py
  tests/integration/connection_test.py
  tests/unit/model/a_d_l_s_object_test.py
  tests/unit/model/connection_test.py
  tests/unit/test_utils.py
Labels: feature

#624 APP-6156: Migrated from `TLS` to `ContextVars` to support both multithreading and async environments
  pyatlan/client/atlan.py
  pyatlan/utils.py
Labels: feature, change

#569 APP-5740 : Add support for iterative pagination to `User`, `Group`, and `Workflow` results
  pyatlan/client/atlan.py
  pyatlan/client/group.py
  pyatlan/client/user.py
  pyatlan/client/workflow.py
  pyatlan/model/user.py
  pyatlan/model/workflow.py
  pyatlan/samples/search/and_star_assets.py
  tests/integration/admin_test.py
  tests/integration/custom_metadata_test.py
  tests/integration/suggestions_test.py
  tests/integration/test_sso_client.py
  tests/integration/test_workflow_client.py
  tests/unit/test_client.py
  tests/unit/test_workflow_client.py
Labels: change

#630 Bump to release 6.1.0
  HISTORY.md
  docs/asset/connectionprocess.rst
  docs/asset/powerbiapp.rst
  docs/asset/saperpcdsview.rst
  docs/asset/snowflakestage.rst
  docs/assets.rst
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/a_d_l_s.py
  pyatlan/model/assets/connection.py
  pyatlan/model/assets/connection_process.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/power_b_i_app.py
  pyatlan/model/assets/core/power_b_i_dashboard.py
  pyatlan/model/assets/core/power_b_i_report.py
  pyatlan/model/assets/core/process.py
  pyatlan/model/assets/core/schema.py
  pyatlan/model/assets/core/snowflake_stage.py
  pyatlan/model/assets/dbt_column_process.py
  pyatlan/model/assets/dbt_process.py
  pyatlan/model/assets/sap_erp_cds_view.py
  pyatlan/model/assets/sap_erp_column.py
  pyatlan/model/assets/sap_erp_component.py
  pyatlan/model/structs.py
  pyatlan/utils.py
  pyatlan/version.txt
Labels: release

#637 APP-6827 Add utility method to facilitate processing assets while iterating thru results of a fluent search.
  pyatlan/client/asset.py
  tests/integration/test_client.py
Labels: feature

#633 APP-6766: Prevent pagination loop break by filtering invalid assets
  pyatlan/client/asset.py
  pyatlan/model/audit.py
  pyatlan/model/search_log.py
  tests/unit/test_client.py
Labels: bugfix

#639 [release] Bump to release `6.1.1`
  HISTORY.md
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/auth_service.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/auth_policy.py
  pyatlan/model/assets/core/column.py
  pyatlan/model/assets/core/cosmos_mongo_d_b_collection.py
  pyatlan/model/assets/core/document_d_b_collection.py
  pyatlan/model/assets/core/dynamo_d_b_secondary_index.py
  pyatlan/model/assets/core/mongo_d_b_collection.py
  pyatlan/model/assets/core/schema.py
  pyatlan/model/assets/core/table.py
  pyatlan/model/assets/dynamo_dbtable.py
  pyatlan/model/assets/tableau_dashboard.py
  pyatlan/model/enums.py
  pyatlan/version.txt
Labels: release

#636 APP-6272 : Update SDKs to use enhanced bulk endpoint for tag mutations
  pyatlan/client/asset.py
  pyatlan/generator/templates/referenceable_attributes.jinja2
  pyatlan/model/assets/core/referenceable.py
  tests/integration/test_client.py
  tests/unit/constants.py
Labels: feature

#643 APP-6766: Added default `typeName=Referenceable` for must clauses
  pyatlan/client/asset.py
  tests/unit/test_client.py
Labels: bugfix

#644 [release] Bump to release `6.2.0`
  HISTORY.md
  docs/asset/tableaudashboardfield.rst
  docs/asset/tableauworksheetfield.rst
  docs/assets.rst
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/a_d_l_s.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/tableau_calculated_field.py
  pyatlan/model/assets/tableau_dashboard.py
  pyatlan/model/assets/tableau_dashboard_field.py
  pyatlan/model/assets/tableau_datasource_field.py
  pyatlan/model/assets/tableau_worksheet.py
  pyatlan/model/assets/tableau_worksheet_field.py
  pyatlan/model/structs.py
  pyatlan/version.txt
Labels: release

#649 Bump to release 6.2.1
  HISTORY.md
  pyatlan/model/assets/core/column.py
  pyatlan/model/structs.py
  pyatlan/version.txt
Labels: release
