Repository atlanhq/atlan-python, pull requests merged in 2025-04, with the labels that each got.

#592 APP-6218: Improve 401 token refresh handling
  pyatlan/client/atlan.py
  tests/integration/test_client.py
Labels: bugfix, change

#593 Bump to release 6.0.2
  HISTORY.md
  pyatlan/client/atlan.py
  pyatlan/generator/templates/methods/attribute/badge.jinja2
  pyatlan/generator/templates/referenceable_methods.jinja2
  pyatlan/version.txt
Labels: release

#595 APP-5915 : Add "Workflow Name" as an optional param in credentials.get_all()
  pyatlan/client/credential.py
Labels: feature

#600 APP-6310: Added support for `purpose` and `persona` in `IndexSearchRequest`
  pyatlan/model/search.py
  tests/integration/test_index_search.py
Labels: feature

#598 APP-5964 : Overload `client.workflow.monitor()` to directly accept `workflow ID/name`
  pyatlan/client/workflow.py
  tests/integration/test_workflow_client.py
  tests/unit/constants.py
Labels: feature

#601 [release] Bump to release `6.0.3`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#602 fix the indentation issue in documentDB jinja template
  pyatlan/generator/templates/methods/asset/document_d_b_collection.jinja2
  pyatlan/generator/templates/methods/asset/document_d_b_database.jinja2
  pyatlan/generator/templates/methods/attribute/document_d_b_collection.jinja2
  pyatlan/generator/templates/methods/attribute/document_d_b_database.jinja2
Labels: change

#606 APP-5774 : Extend tagged with value search with option for specific source tag
  pyatlan/model/fluent_search.py
Labels: feature

#607 APP-6398: Allow extra fields in `AtlanYamlModel` (`Extra.allow`) to support undefined contract fields
  pyatlan/model/contract.py
  pyatlan/model/core.py
  tests/integration/test_sql_assets.py
Labels: feature, bugfix

#604 APP-5600 : Enhance Python SDK to support workflow-run search by status and interval
  pyatlan/client/workflow.py
  tests/integration/test_workflow_client.py
  tests/unit/test_workflow_client.py
Labels: feature

#613 [req-changes] Renamed method name to `init_for_multithreading` for more clarity
  pyatlan/client/atlan.py
Labels: change

#612 APP-6435: Added support for `vcrpy` test utilities to mock `HTTP` interactions with 3rd-party `APIs`
  .github/workflows/pyatlan-pr.yaml
  pyatlan/errors.py
  pyatlan/test_utils/__init__.py
  pyatlan/test_utils/base_vcr.py
  requirements-dev.txt
  tests/unit/conftest.py
  tests/unit/test_base_vcr_json.py
  tests/unit/test_base_vcr_yaml.py
  tests/vcr_cassettes/tests.unit.test_base_vcr_json/TestBaseVCRJSON.test_httpbin_delete.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_json/TestBaseVCRJSON.test_httpbin_get.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_json/TestBaseVCRJSON.test_httpbin_post.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_json/TestBaseVCRJSON.test_httpbin_put.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_yaml/TestBaseVCRYAML.test_httpbin_delete.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_yaml/TestBaseVCRYAML.test_httpbin_get.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_yaml/TestBaseVCRYAML.test_httpbin_post.yaml
  tests/vcr_cassettes/tests.unit.test_base_vcr_yaml/TestBaseVCRYAML.test_httpbin_put.yaml
Labels: test

#619 [release] Bump to release `6.0.6`
  HISTORY.md
  pyatlan/version.txt
Labels: release
