Repository atlanhq/atlan-python, pull requests merged in 2025-07, with the labels that each got.

#674 [test] Fixed `suggestions_test` and added `delete_type` param to `purge_by_guid()` method
  pyatlan/client/asset.py
  tests/integration/client.py
  tests/integration/suggestions_test.py
Labels: refactor

#682 [release] Bumped to release `7.1.3`
  .dockerignore
  HISTORY.md
  MANIFEST.in
  README.md
  containers/.dockerignore
  pyatlan/version.txt
Labels: release

#686 APP-7827: Added support for `AttributeDef.Options.applicable_ai_asset_types`
  pyatlan/model/constants.py
  pyatlan/model/typedef.py
  tests/unit/constants.py
  tests/unit/test_typedef_model.py
Labels: feature

#684 APP-7029 : Add creator() for AI-based assets
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/a_i_application.jinja2
  pyatlan/generator/templates/methods/asset/a_i_model.jinja2
  pyatlan/generator/templates/methods/asset/process.jinja2
  pyatlan/generator/templates/methods/attribute/a_i_application.jinja2
  pyatlan/generator/templates/methods/attribute/a_i_model.jinja2
  pyatlan/generator/templates/methods/attribute/process.jinja2
  pyatlan/generator/templates/module.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/assets/core/a_i_application.py
  pyatlan/model/assets/core/a_i_model.py
  pyatlan/model/assets/core/process.py
  pyatlan/model/enums.py
  pyatlan/model/structs.py
  tests/integration/ai_asset_test.py
  tests/unit/model/a_i_application_test.py
  tests/unit/model/a_i_model_test.py
  tests/unit/model/constants.py
Labels: feature

#688 APP-7889: Fixed handling of `source_tag` when no attributes present
  pyatlan/model/translators.py
  tests/unit/test_atlan_tag_name.py
Labels: bugfix

#685 APP-7824: Added support for `AtlanClient` creation via api token `guid`
  pyatlan/client/atlan.py
  pyatlan/errors.py
  tests/integration/test_client.py
Labels: feature
