Repository atlanhq/atlan-python, pull requests merged in 2025-03, with the labels that each got.

#548 APP-5657 : Add support for `MatchPhase` query to the SDKs
  pyatlan/model/fields/atlan_fields.py
  pyatlan/model/search.py
  tests/unit/test_search_model.py
Labels: feature

#553 APP-5738: Added support for handling `aggregations` in the `AuditSearchResults`
  pyatlan/client/audit.py
  pyatlan/model/audit.py
  tests/unit/data/search_responses/audit_search_paging.json
  tests/unit/test_audit_search.py
Labels: bugfix

#554 [deps] Bump ruff to the latest version
  requirements-dev.txt
Labels: dependencies

#555 [release] Bump to release `5.0.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#566 APP-5595: Added handling for `doc` / `errorDoc` in `AtlanError`
  pyatlan/client/atlan.py
  pyatlan/errors.py
  tests/unit/test_client.py
Labels: feature

#567 [release] Bump to release `5.0.2`
  .github/workflows/pyatlan-pr.yaml
  HISTORY.md
  pyatlan/version.txt
Labels: release

#568 APP=5912 | Add documentdb connectorType
  pyatlan/model/enums.py
Labels: feature

#573 APP-5519: Migrated `AtlanClient._default_client` to thread-local storage + caches now bound to optional client
  pyatlan/cache/abstract_asset_cache.py
  pyatlan/cache/atlan_tag_cache.py
  pyatlan/cache/connection_cache.py
  pyatlan/cache/custom_metadata_cache.py
  pyatlan/cache/enum_cache.py
  pyatlan/cache/group_cache.py
  pyatlan/cache/role_cache.py
  pyatlan/cache/source_tag_cache.py
  pyatlan/cache/user_cache.py
  pyatlan/client/asset.py
  pyatlan/client/atlan.py
  pyatlan/client/open_lineage.py
  pyatlan/client/typedef.py
  pyatlan/client/user.py
  pyatlan/generator/templates/methods/asset/data_product.jinja2
  pyatlan/generator/templates/methods/asset/purpose.jinja2
  pyatlan/generator/templates/methods/attribute/connection.jinja2
  pyatlan/model/assets/badge.py
  pyatlan/model/assets/connection.py
  pyatlan/model/assets/core/data_product.py
  pyatlan/model/assets/core/referenceable.py
  pyatlan/model/assets/purpose.py
  pyatlan/model/core.py
  pyatlan/model/custom_metadata.py
  pyatlan/model/fields/atlan_fields.py
  pyatlan/model/fluent_search.py
  pyatlan/model/open_lineage/event.py
  pyatlan/model/search.py
  pyatlan/model/structs.py
  pyatlan/model/suggestions.py
  pyatlan/model/typedef.py
  pyatlan/samples/events/lambda_scorer.py
  pyatlan/test_utils/__init__.py
  tests/integration/admin_test.py
  tests/integration/atlan_tag_test.py
  tests/integration/connection_test.py
  tests/integration/custom_metadata_test.py
  tests/integration/test_open_lineage.py
  tests/integration/test_sql_assets.py
  tests/unit/model/badge_test.py
  tests/unit/model/connection_test.py
  tests/unit/test_atlan_tag_name.py
  tests/unit/test_client.py
  tests/unit/test_connection_cache.py
  tests/unit/test_core.py
  tests/unit/test_custom_metadata.py
  tests/unit/test_events.py
  tests/unit/test_model.py
  tests/unit/test_packages.py
  tests/unit/test_source_cache.py
  tests/unit/test_structs.py
  tests/unit/test_typedef_model.py
Labels: change

#575 APP-5956 : Add custom `AtlanError` for the `DataProduct.get_assets` method
  pyatlan/errors.py
  pyatlan/generator/templates/methods/asset/data_product.jinja2
  pyatlan/model/assets/core/data_product.py
  tests/unit/model/data_product_test.py
Labels: feature

#577 [release] Bump to release `6.0.0`
  HISTORY.md
  pyatlan/client/atlan.py
  pyatlan/version.txt
Labels: release

#583 APP-6125 : Pyatlan changes to token refresh
  pyatlan/client/atlan.py
Labels: feature
