Repository atlanhq/atlan-python, pull requests merged in 2025-02, with the labels that each got.

#491 APP-5019: Add `CrendentialClient.creator()` (with the optional "host" and "port" params)
  pyatlan/client/constants.py
  pyatlan/client/credential.py
  pyatlan/client/open_lineage.py
  pyatlan/model/assets/connection.py
  pyatlan/model/credential.py
  tests/integration/test_workflow_client.py
  tests/unit/test_credential_client.py
Labels: feature

#496 APP-5077: Changed default for tracking search logs (`save_search_log=False`)
  pyatlan/model/search.py
  tests/unit/data/search_responses/aggregations_null_value.json
  tests/unit/data/search_responses/index_search_paging.json
  tests/unit/test_search_model.py
Labels: change

#495 [release] Bump to release `4.2.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#497 [ci] Updated `actions/upload-artifact` GH action to `v4`
  .github/workflows/pyatlan-publish.yaml
Labels: change

#498 APP-5297: Make 'test' parameter optional in credential `creator()` method
  pyatlan/client/credential.py
Labels: feature

#500 [release] Bump to release `4.2.1`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#499 APP-5087 | added adlsContainerName and adlsAccountName attributes
  pyatlan/model/assets/a_d_l_s.py
  pyatlan/model/assets/a_d_l_s_container.py
  pyatlan/model/assets/a_d_l_s_object.py
  tests/integration/adls_asset_test.py
Labels: feature

#502 APP-5136 : Addition of new connectors
  .pre-commit-config.yaml
  pyatlan/model/enums.py
Labels: feature

#501 APP-4979 : Anaplan System Dimension - Addition
  docs/asset/anaplansystemdimension.rst
  docs/asset/sourcetag.rst
  docs/assets.rst
  pyatlan/generator/templates/methods/asset/anaplan_system_dimension.jinja2
  pyatlan/generator/templates/methods/asset/connection.jinja2
  pyatlan/model/assets/__init__.py
  pyatlan/model/assets/__init__.pyi
  pyatlan/model/assets/anaplan_system_dimension.py
  pyatlan/model/assets/core/__init__.py
  pyatlan/model/structs.py
  tests/integration/anaplan_asset_test.py
  tests/unit/model/anaplan_system_dimension_test.py
  tests/unit/model/constants.py
Labels: feature

#504 [release] Bump to release `4.2.2`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#507 [release] Bump to release `4.2.3`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#508 APP-5411: Added safeguards for search pagination methods
  pyatlan/client/asset.py
  pyatlan/model/audit.py
  pyatlan/model/search_log.py
Labels: bug

#509 [release] Bump to release `4.2.4`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#511 [ci] Added `dependabot.yml` and removed unused secret variables
  .github/dependabot.yml
  .github/workflows/pyatlan-pr.yaml
  .github/workflows/pyatlan-test-cron.yaml
Labels: dependencies

#529 APP-5498 : Fix integration tests broken for Glossary Terms
  tests/integration/test_client.py
Labels: bugfix

#531 APP-5434: Added `errorCause` property to error message response payloads
  pyatlan/client/atlan.py
  pyatlan/errors.py
  tests/unit/test_client.py
Labels: feature

#533 APP-5220: Added SDK version number to the `_api_logger()` method
  pyatlan/client/atlan.py
Labels: feature

#505 APP-4750: Add creators for `Quicksight` assets
  pyatlan/generator/templates/methods/asset/quick_sight_analysis.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_analysis_visual.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_dashboard.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_dashboard_visual.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_dataset.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_dataset_field.jinja2
  pyatlan/generator/templates/methods/asset/quick_sight_folder.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_analysis.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_analysis_visual.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_dashboard.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_dashboard_visual.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_dataset.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_dataset_field.jinja2
  pyatlan/generator/templates/methods/attribute/quick_sight_folder.jinja2
  pyatlan/model/assets/quick_sight_analysis.py
  pyatlan/model/assets/quick_sight_analysis_visual.py
  pyatlan/model/assets/quick_sight_dashboard.py
  pyatlan/model/assets/quick_sight_dashboard_visual.py
  pyatlan/model/assets/quick_sight_dataset.py
  pyatlan/model/assets/quick_sight_dataset_field.py
  pyatlan/model/assets/quick_sight_folder.py
  tests/integration/adls_asset_test.py
  tests/integration/airflow_asset_test.py
  tests/integration/anaplan_asset_test.py
  tests/integration/api_asset_test.py
  tests/integration/app_asset_test.py
  tests/integration/azure_event_hub_asset_test.py
  tests/integration/custom_asset_test.py
  tests/integration/data_mesh_test.py
  tests/integration/data_studio_asset_test.py
  tests/integration/gcs_asset_test.py
  tests/integration/insights_test.py
  tests/integration/kafka_asset_test.py
  tests/integration/preset_asset_test.py
  tests/integration/quick_sight_asset_test.py
  tests/integration/s3_asset_test.py
  tests/integration/superset_asset_test.py
  tests/integration/utils.py
  tests/unit/model/constants.py
  tests/unit/model/quick_sight_analysis_test.py
  tests/unit/model/quick_sight_analysis_visual_test.py
  tests/unit/model/quick_sight_dashboard_test.py
  tests/unit/model/quick_sight_dashboard_visual_test.py
  tests/unit/model/quick_sight_dataset_field_test.py
  tests/unit/model/quick_sight_dataset_test.py
  tests/unit/model/quick_sight_folder_test.py
Labels: feature

#530 APP-5338 | Add connector types CrateDB and KX
  pyatlan/model/enums.py
Labels: feature

#536 [release] Bump to release `4.2.5`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#535 APP-5412 : Change the Query Model to use Pydantic model
  pyatlan/model/search.py
  tests/unit/test_search_model.py
Labels: change

#541 APP-5632: Handled `SearchLogResults` edge cases - when `entityGuidsAll` is empty `[]` or `"undefined"` in the request DSL
  pyatlan/model/search_log.py
  pyatlan/utils.py
Labels: bugfix

#540 APP-4932: Changeed default behavior for tag propagation to `False`
  pyatlan/client/asset.py
  pyatlan/client/atlan.py
  pyatlan/model/core.py
Labels: breaking-change

#545 [gen/templates] Fixed generator templates (as per recent updates)
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/data_product.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_container.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_object.jinja2
  pyatlan/generator/templates/module.jinja2
  pyatlan/model/assets/a_d_l_s_container.py
  pyatlan/model/assets/a_d_l_s_object.py
  pyatlan/model/assets/core/data_product.py
Labels: bugfix

#538 APP-5521 | Ensure separation of attributes for `S3`, `GCS` and `ADLS` creators
  pyatlan/generator/templates/imports.jinja2
  pyatlan/generator/templates/methods/asset/a_d_l_s_object.jinja2
  pyatlan/generator/templates/methods/asset/g_c_s_object.jinja2
  pyatlan/generator/templates/methods/asset/s3_object.jinja2
  pyatlan/generator/templates/methods/attribute/a_d_l_s_object.jinja2
  pyatlan/generator/templates/methods/attribute/g_c_s_object.jinja2
  pyatlan/generator/templates/methods/attribute/s3_object.jinja2
  pyatlan/model/assets/a_d_l_s_object.py
  pyatlan/model/assets/g_c_s_object.py
  pyatlan/model/assets/s3_object.py
  pyatlan/model/utils.py
  tests/integration/adls_asset_test.py
  tests/integration/gcs_asset_test.py
  tests/unit/model/a_d_l_s_object_test.py
  tests/unit/model/constants.py
  tests/unit/model/gcs_object_test.py
  tests/unit/model/s3_object_test.py
  tests/unit/test_utils.py
Labels: breaking-change

#547 [release] Bump to release `5.0.0`
  HISTORY.md
  pyatlan/version.txt
Labels: release

#546 APP-5676: Remove redundant asset relationship fields
  pyatlan/generator/templates/macros.jinja2
  pyatlan/generator/templates/methods/asset/asset.jinja2
  pyatlan/generator/templates/referenceable_attributes.jinja2
  pyatlan/generator/templates/referenceable_methods.jinja2
  pyatlan/model/assets/core/asset.py
  pyatlan/model/assets/core/referenceable.py
Labels: change
